import { useEffect, useState } from 'react';
import { Amplify } from 'aws-amplify';
import { withAuthenticator, Button, Heading } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

import config from '../amplify_outputs.json'; // This file is generated by the Amplify CLI

Amplify.configure(config);

function App({ signOut, user }) {
  const [notes, setNotes] = useState([]);

  useEffect(() => {
    // You would typically fetch notes from your backend here
    console.log("Fetching notes...");
    // Example: Amplify.API.get('notesApi', '/notes', {}).then(data => setNotes(data));
  }, []);

  return (
    <div>
      <header>
        <Heading level={1}>Hello {user.username}</Heading>
        <Button onClick={signOut}>Sign Out</Button>
      </header>
      <main>
        {/* Your application's main content goes here */}
        <p>You have successfully logged in.</p>
        {/* Example of a form to add a new note */}
      </main>
    </div>
  );
}

export default withAuthenticator(App);
